name: Movie Bot

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find bot.py
        run: |
          echo "WORKSPACE:"
          echo "$GITHUB_WORKSPACE"

          echo "GIT COMMIT:"
          git rev-parse HEAD

          echo "FILES IN GIT:"
          git ls-tree -r --name-only HEAD

          echo "SEARCH BOT:"
          find "$GITHUB_WORKSPACE" -type f -name "bot.py" -print

      - name: Stop here
        run: echo "TEST FINISHED"
